name: Build and Deploy Jekyll Site for English

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: BioInfoCommunity/course-template/.github/workflows/deploy.yml@main
    with:
      lang: en
    permissions:
      contents: write
