name: Lint PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    uses: BioInfoCommunity/course-template/.github/workflows/lint.yml@main
    permissions:
      contents: read
      pull-requests: write
